// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bKpefHuncX8cEW37wPMjAY
// Component: AB8JaR2qqP1j
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: 8kOegrLbSihG/component
import Button from "../../Button"; // plasmic-import: whXBuzPs67oZ/component
import ProductCard from "../../ProductCard"; // plasmic-import: 7yo9Dsbre-qP/component
import Footer from "../../Footer"; // plasmic-import: 1SCnhMzCyJ6Q/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qZ9zHZTyMfkd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: bKpefHuncX8cEW37wPMjAY/projectcss
import * as sty from "./PlasmicCategory.module.css"; // plasmic-import: AB8JaR2qqP1j/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: wH-q_ZHHI5xE/icon
import Icon33Icon from "./icons/PlasmicIcon__Icon33"; // plasmic-import: _D_aNlnfEAWU/icon
import Icon34Icon from "./icons/PlasmicIcon__Icon34"; // plasmic-import: mArF2tXHPomf/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: EgDL1U1mt1UT/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: L4effzobDuu0/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: gmxW2ng1jNY9/icon

export type PlasmicCategory__VariantMembers = {};

export type PlasmicCategory__VariantsArgs = {};
type VariantPropType = keyof PlasmicCategory__VariantsArgs;
export const PlasmicCategory__VariantProps = new Array<VariantPropType>();

export type PlasmicCategory__ArgsType = {};
type ArgPropType = keyof PlasmicCategory__ArgsType;
export const PlasmicCategory__ArgProps = new Array<ArgPropType>();

export type PlasmicCategory__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  section?: p.Flex<"section">;
  container6?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
  textbox?: p.Flex<"input">;
};

export interface DefaultCategoryProps {
  className?: string;
}

function PlasmicCategory__RenderFunc(props: {
  variants: PlasmicCategory__VariantsArgs;
  args: PlasmicCategory__ArgsType;
  overrides: PlasmicCategory__OverridesType;
  dataFetches?: PlasmicCategory__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen" as const}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__mRsX0)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___0XD)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__grIrq
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__e3Kho)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__gm86B
                        )}
                      >
                        {"All"}
                      </div>
                    }
                    states={"active" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__cP23)}
                    icons={"none" as const}
                    slot={"New"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__flX7)}
                    icons={"none" as const}
                    slot={"Womens"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__m3Sb)}
                    icons={"none" as const}
                    slot={"Mens"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__zFIfN)}
                    icons={"none" as const}
                    slot={"Kids"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__twCn1)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__moiZ2
                        )}
                      >
                        {"On sale"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__yoIyb)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gcdZd
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__ul0P4)}
                    icons={"none" as const}
                    slot={"$0 - $50"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__c5ICi)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__dKdPv
                        )}
                      >
                        {"$51 - $99"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__o1Rs)}
                    icons={"none" as const}
                    slot={"$101+"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__wTgb)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bouMl
                    )}
                  >
                    {"Colors"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__u2TT)}
                  >
                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__x0OJ
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__s6S5H)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__wlwrW
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__sWkUt)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___2GkQy
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__hrB8H)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__btkd3
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__wlLlu)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__xm48U
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__s9Let)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__fjd0O
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__ix6Vu)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__bzbkm
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__qWsDb)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__dUuQk
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__sss8X)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__d9Ah3
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__jhja1)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__iNcVm
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__cUosp)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__t9VUe
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg___3NNv)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___8WDlx
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__nBcmn)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__r1G6F
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg___4Y5Bo)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___0DBmY
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon33Icon
                        className={classNames(defaultcss.all, sty.svg__d0URu)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      icons={"only" as const}
                      size={"narrow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text___5HZmj
                          )}
                        >
                          {"Adidas"}
                        </div>
                      }
                    >
                      <Icon34Icon
                        className={classNames(defaultcss.all, sty.svg__cSIx)}
                        role={"img"}
                      />
                    </Button>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__dq6LK)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__iUyUm
                    )}
                  >
                    {"Brands"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__xkA3X)}
                    icons={"none" as const}
                    slot={"Adidas"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___2IjvV)}
                    icons={"none" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__cktag
                        )}
                      >
                        {"Asics"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__vSiyt)}
                    icons={"none" as const}
                    slot={"Crocs"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__ooflG)}
                    icons={"none" as const}
                    slot={"Fila"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__tw0Xd)}
                    icons={"none" as const}
                    slot={"Nike"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__opaSh)}
                    icons={"none" as const}
                    slot={"Puma"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__r7UH)}
                    icons={"none" as const}
                    slot={"Reebok"}
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__pJjCu)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tvfA0
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__w6Bl)}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/0a659aab-5bb4-471e-adb3-beaf9be6e737/air-zoom-pegasus-38-limited-edition-womens-running-shoe-vmTQVG.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bPDmc
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fhQxV
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__i5K1G
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__jf9Wr)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__l1HW
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___9Emvo
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gpln4
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__cClhs)}
                      src={
                        "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___08VDb
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rrrpS
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___90U3H
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__g2FJe)}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rNtYs
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__s5Xa
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__h69El
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__hc250)}
                      src={
                        "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yNpis
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__w3Xg
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__u6Pl8
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__r7U4J)}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ibmL9
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z1MnY
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pwlca
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___5Ea9)}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ytAoK
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___4Nqc9
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cgWGe
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__c5LlF)}
                      src={
                        "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__a2Xat
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___7MpIn
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__n9Xt3
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__hnye2)}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fAyZt
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___7Bcf9
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wsRrs
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__h2CTl)}
                      src={
                        "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__esoEv
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__knu9L
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gqAJ
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__eLzY)}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kt31
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fXwTh
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vboJb
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__clpGt)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__flXbf
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___3WVdl
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___1TlW6
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__qZ1Aq)}
                      src={
                        "https://pyxis.nymag.com/v1/imgs/537/58a/ddd6aab90b2387c93d86216de49dccfe4b-madewell-court-sneaker.2x.rsquare.w600.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__iLtYg
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z8RgO
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aRd6I
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__e6Dpl)}
                      src={
                        "https://cdn.shopify.com/s/files/1/2495/5044/products/oca-low-green-canvas-sneaker.slideshow1.jpg?v=1610694945" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hCoGy
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__weTWm
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fBvck
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___18Yk)}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/38277b478a79419abf6da998000ab640_9366/Runfalcon_Shoes_Black_F36218_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fRc75
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ziJpP
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__kVYw3
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__tZk6D)}
                      src={
                        "https://assets.adidas.com/images/w_600,f_auto,q_auto/4e894c2b76dd4c8e9013aafc016047af_9366/Superstar_Shoes_White_FV3284_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xopQu
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kgvW
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__b1BbA)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hBYh7
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___2XOwk
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…" as const}
                    size={1 as const}
                    type={"text" as const}
                    value={"" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__kZJjo)}
                    colors={"black" as const}
                    icons={"none" as const}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__v0Hd)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lnfvD
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__a0Oj3)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__cz21P)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___3KCo2
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__f5Juj
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__njmrq)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__f7NB2
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.text__uu70
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__kZ8V)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__uwzV3)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__k9HI
                    )}
                  >
                    {"More info"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__i6Yq1)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__pl3An)}
                    >
                      <Button icons={"none" as const} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ghWLw
                        )}
                        icons={"none" as const}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__pds0G
                        )}
                        icons={"none" as const}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__nxQHv
                        )}
                        icons={"none" as const}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__fnxnK)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__zRa0D
                        )}
                        icons={"none" as const}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__vOwtp
                        )}
                        icons={"none" as const}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__xgrm4
                        )}
                        icons={"none" as const}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer", "textbox"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  section: "section";
  container6: "div";
  footer: typeof Footer;
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCategory__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCategory__VariantsArgs;
    args?: PlasmicCategory__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCategory__Fetches;
  } & Omit<PlasmicCategory__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCategory__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCategory__ArgProps,
      internalVariantPropNames: PlasmicCategory__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCategory__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCategory";
  } else {
    func.displayName = `PlasmicCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicCategory = Object.assign(
  // Top-level PlasmicCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicCategory
    internalVariantProps: PlasmicCategory__VariantProps,
    internalArgProps: PlasmicCategory__ArgProps
  }
);

export default PlasmicCategory;
/* prettier-ignore-end */
